// =====================================================
// IMPORTS
// =====================================================
import { useState, useRef, useEffect, useCallback, Fragment } from "react";
import "../styles/preprocessing.css";
 
/* =====================================================================
   Pre-Processing Pipeline Studio  (Ambient Scientific · GPX)  — v3.1
 
   What changed in v3.1 (layout / copy only — codegen untouched):
     · "Choose your variant" heading -> "Choose pre-processing route".
     · Path 01–03 descriptions rewritten to describe the 256-point FFT route.
     · Flow-diagram nodes now share ONE uniform rounded-rect shape.
     · Diagram node/IO labels enlarged (were unreadable at scaled SVG — CSS).
     · Capture readout drops the raw "smp" count; Features hint removed;
       "Frame tiling" label shortened to "Frame".
     · Hero title vertically centred (CSS).
   ===================================================================== */
 
 
// =====================================================
// HARDWARE CONSTANTS  (mirror Feature-Extraction.py)
// =====================================================
const SAMPLE_RATE = 8000;  // Hz — 1 sample = 0.125 ms
const FRAME_LEN = 256;   // samples per frame = 32 ms
const MIN_FRAMES = 1;     // 1 frame  = 256 samples = 32 ms
const MAX_SECONDS = 5;     // hard cap: 5 s of audio
const MAX_FRAMES = Math.floor((MAX_SECONDS * SAMPLE_RATE) / FRAME_LEN); // 156 frames ≈ 4.992 s
 
// Static procedural waveform for the frame-tiling strip (scaled by viewBox).
const WAVE = (() => {
  const N = 240, W = 1000, H = 64, mid = H / 2, amp = 22;
  let pts = "";
  for (let i = 0; i < N; i++) {
    const t = i / (N - 1);
    const env = Math.pow(Math.sin(Math.PI * t), 0.75);
    let y =
      Math.sin(t * 20 * Math.PI) * 0.55 +
      Math.sin(t * 47 * Math.PI + 1) * 0.24 +
      Math.sin(t * 97 * Math.PI + 2) * 0.13;
    y *= env;
    pts += (i ? " " : "") + (t * W).toFixed(1) + "," + (mid - y * amp).toFixed(1);
  }
  return { pts, W, H };
})();
 
 
// =====================================================
// CODE GENERATION (pure helpers)   — unchanged
// =====================================================
 
// Right-pad a value with spaces so the trailing comments line up.
function pad(value) {
  const text = String(value);
  return " ".repeat(Math.max(1, 9 - text.length));
}
 
// ---------------------------------------------------------------------
// PATHS 01–03  —  preprocess() only (FFT / Square·Shift / Saturate)
// ---------------------------------------------------------------------
function buildCode(state) {
  const square = state.square;
  const saturate = state.saturate;
  const lines = [];
 
  const stages = [
    "FFT",
    square ? "Square" : null,
    square ? "Shift" : null,
    saturate ? "Saturate" : null,
  ].filter(Boolean);
 
  const bar = "=".repeat(70);
 
  // ----- File header -----
  lines.push("# " + bar);
  lines.push("# Ambient Scientific  -  GPX audio front-end (pre-processing)");
  lines.push("# Auto-generated by the Pre-Processing Pipeline Studio");
  lines.push("#");
  lines.push("# Selected hardware path : " + stages.join("  ->  "));
  lines.push("# Source of truth        : Feature-Extraction.py  (frames2feature)");
  lines.push("# " + bar);
  lines.push("");
  lines.push("import numpy as np");
  lines.push("");
 
  // ----- Tweakable hardware parameters -----
  lines.push("# ----- Tweakable hardware parameters ---------------------------------");
  lines.push("FRAME_SIZE = " + state.frame + pad(state.frame) + "# samples per FFT frame  (HW FIFO depth = 256)");
  lines.push("FFT_SHIFT  = " + state.fftShift + pad(state.fftShift) + "# real-FFT output right-shift   (>> " + state.fftShift + ")");
  if (square) {
    lines.push("SQR_SHIFT  = " + state.sqrShift + pad(state.sqrShift) + "# post-square right-shift       (>> " + state.sqrShift + ")");
  }
  if (saturate) {
    lines.push("SAT_MAX    = " + state.satMax + pad(state.satMax) + "# saturation clamp value (int16 max)");
  }
  lines.push("# ---------------------------------------------------------------------");
  lines.push("");
  lines.push("");
 
  // ----- chop_array() helper -----
  lines.push("def chop_array(arr, window_size, hop_size):");
  lines.push('    """Slice a 1-D signal into non-overlapping frames (window == hop)."""');
  lines.push("    return [arr[i - window_size:i]");
  lines.push("            for i in range(window_size, len(arr) + 1, hop_size)]");
  lines.push("");
  lines.push("");
 
  // ----- preprocess() -----
  lines.push("def preprocess(audio):");
  lines.push('    """Replicate the GPX hardware audio front-end in integer arithmetic.');
  lines.push("");
  lines.push("    Active stages:  " + stages.join("  ->  "));
  lines.push('    """');
  lines.push("    frames = np.short(chop_array(audio, FRAME_SIZE, FRAME_SIZE))");
  lines.push("    output = []");
  lines.push("");
  lines.push("    for frame in frames:");
  lines.push("        frame = np.short(frame)");
  lines.push("");
  lines.push("        # --- FFT (mandatory) -----------------------------------------");
  lines.push("        spec = np.fft.fft(frame)");
  lines.push("        spec = np.int32(spec.real)          # keep the real part");
  lines.push("        spec = spec >> FFT_SHIFT            # fixed-point rescale");
  lines.push("        spec = np.short(spec)");
 
if (!square) {
    lines.push("        output.append(spec)                # <-- FFT-only output");
  } else {
    lines.push("");
    lines.push("        # --- Square + Shift ------------------------------------------");
    lines.push('        spec = spec.astype("int32") ** 2    # power of each freq bin');
    lines.push("        spec = spec >> SQR_SHIFT           # rescale toward 16-bit");

    if (!saturate) {
      lines.push("");
      lines.push("        # --- HW output register is 16-bit signed--------------------");
      lines.push("        spec = np.array(spec & 0xFFFF, dtype=np.uint16).view(np.int16)");
      lines.push("");
      lines.push("        output.append(spec)                # <-- square+shift output (int16)");
    } else {
      lines.push("");
      lines.push("        # --- Saturate ------------------------------------------------");
      lines.push("        spec[spec > SAT_MAX] = 0xFFFF");
      lines.push("        spec = np.array(spec & 0xFFFF, dtype=np.uint16).view(np.int16)");
      lines.push("        output.append(spec)                # <-- saturated output");
    }
  }
 
  lines.push("");
  lines.push("    return output");
  lines.push("");
  lines.push("");
 
  // ----- demo entry point -----
  lines.push('if __name__ == "__main__":');
  lines.push("    dummy = np.random.randint(-2000, 2000, FRAME_SIZE).astype(np.short)");
  lines.push("    feats = preprocess(dummy)");
  lines.push('    print("frames:", len(feats), "| bins/frame:", np.asarray(feats).shape)');
 
  return lines.join("\n");
}
 
// ---------------------------------------------------------------------
// PATH 04  —  FULL feature pipeline (mirrors Feature-Extraction.py).
// ---------------------------------------------------------------------
function buildFullCode(state) {
  const nf = state.features;
  const cap = state.capture;
  const frames = Math.max(0, Math.floor(cap / state.frame));
  const ms = ((cap / SAMPLE_RATE) * 1000).toFixed(0);
  const bar = "=".repeat(70);
  const L = [];
 
  // ----- File header -----
  L.push("# " + bar);
  L.push("# Ambient Scientific  -  GPX audio front-end  (FULL feature pipeline)");
  L.push("# Auto-generated by the Pre-Processing Pipeline Studio");
  L.push("#");
  L.push("# Selected path       : FFT -> Square -> Shift -> Saturate -> Mel -> Accumulate -> Log");
  L.push("# Features (num_filt) : " + nf);
  L.push("# Capture length      : " + cap + " samples  (" + frames + " frame" + (frames === 1 ? "" : "s") + " of " + state.frame + " = " + ms + " ms @ 8 kHz)");
  L.push("# Source of truth      : Feature-Extraction.py  (frames2feature)");
  L.push("# " + bar);
  L.push("");
  L.push("import numpy as np");
  L.push("");
 
  // ----- Tweakable hardware parameters -----
  L.push("# ----- Tweakable hardware parameters ---------------------------------");
  L.push("SAMPLE_RATE = 8000" + pad(8000) + "# audio sample rate (Hz)");
  L.push("FRAME_SIZE  = " + state.frame + pad(state.frame) + "# samples per FFT frame  (HW FIFO depth = 256 = 32 ms)");
  L.push("CAPTURE_LEN = " + cap + pad(cap) + "# total samples/clip: " + frames + " frames x 256 (32 ms each)");
  L.push("NUM_FILT    = " + nf + pad(nf) + "# mel features emitted per frame");
  L.push("FFT_SHIFT   = " + state.fftShift + pad(state.fftShift) + "# real-FFT output right-shift  (>> " + state.fftShift + ")");
  L.push("SQR_SHIFT   = " + state.sqrShift + pad(state.sqrShift) + "# post-square right-shift      (>> " + state.sqrShift + ")");
  L.push("SAT_MAX     = " + state.satMax + pad(state.satMax) + "# saturation clamp value (int16 max)");
  L.push("# ---------------------------------------------------------------------");
  L.push("");
  L.push("");
 
  // ----- chop_array() -----
  L.push("def chop_array(arr, window_size, hop_size):");
  L.push('    """Slice a 1-D signal into non-overlapping frames (window == hop)."""');
  L.push("    return [arr[i - window_size:i]");
  L.push("            for i in range(window_size, len(arr) + 1, hop_size)]");
  L.push("");
  L.push("");
 
  // ----- safe_log() -----
  L.push("def safe_log(x):");
  L.push('    """log2 (matches the hardware log block)."""');
  L.push("    return np.log2(x)");
  L.push("");
  L.push("");
 
  // ----- filterbanks() -----
  L.push("def filterbanks(sample_rate, num_filt, fft_len):");
  L.push('    """Triangle filters on a mel grid, quantized to int8 weights (0..32)."""');
  L.push("    def hertz_to_mels(f):");
  L.push("        return 1127. * np.log(1. + f / 700.)");
  L.push("");
  L.push("    def mel_to_hertz(mel):");
  L.push("        return 700. * (np.exp(mel / 1127.) - 1.)");
  L.push("");
  L.push("    def correct_grid(x):");
  L.push('        """Push duplicate points forward so no filter has zero width."""');
  L.push("        offset = 0");
  L.push("        for prev, i in zip([x[0] - 1] + list(x), x):");
  L.push("            offset = max(0, offset + prev + 1 - i)");
  L.push("            yield i + offset");
  L.push("");
  L.push("    grid_mels    = np.linspace(hertz_to_mels(0), hertz_to_mels(sample_rate), num_filt + 2, True)");
  L.push("    grid_hertz   = mel_to_hertz(grid_mels)");
  L.push("    grid_indices = (grid_hertz * fft_len / sample_rate).astype(int)");
  L.push("    grid_indices = list(correct_grid(grid_indices))");
  L.push("");
  L.push("    banks = np.zeros([num_filt, fft_len])");
  L.push("    for i, (left, middle, right) in enumerate(chop_array(grid_indices, 3, 1)):");
  L.push("        banks[i, left:middle]  = np.linspace(0., 1., middle - left, False)");
  L.push("        banks[i, middle:right] = np.linspace(1., 0., right - middle, False)");
  L.push("    return banks");
  L.push("");
  L.push("");
 
  // ----- preprocess() -----
  L.push("def preprocess(audio):");
  L.push('    """Full GPX feature front-end in integer arithmetic.');
  L.push("");
  L.push("    FFT -> Square -> Shift -> Saturate -> Mel filterbank -> Accumulate -> Log");
  L.push('    """');
  L.push("    # pad / trim every clip to exactly CAPTURE_LEN samples");
  L.push("    audio = np.asarray(audio)");
  L.push("    if len(audio) < CAPTURE_LEN:");
  L.push('        audio = np.pad(audio, (0, CAPTURE_LEN - len(audio)), mode="constant")');
  L.push("    elif len(audio) > CAPTURE_LEN:");
  L.push("        audio = audio[-CAPTURE_LEN:]");
  L.push("");
  L.push("    frames   = np.short(chop_array(audio, FRAME_SIZE, FRAME_SIZE))");
  L.push("    filters  = filterbanks(SAMPLE_RATE, NUM_FILT, FRAME_SIZE)");
  L.push('    intfltrs = np.array(filters * 32).round().astype("int8")');
  L.push("");
  L.push("    output = []");
  L.push("    for frame in frames:");
  L.push("        frame = np.short(frame)");
  L.push("");
  L.push("        # --- FFT ------------------------------------------------------");
  L.push("        spec = np.fft.fft(frame)");
  L.push("        spec = np.int32(spec.real) >> FFT_SHIFT");
  L.push("        spec = np.short(spec)");
  L.push("");
  L.push("        # --- Square + Shift ------------------------------------------");
  L.push('        spec = spec.astype("int32") ** 2');
  L.push("        spec = spec >> SQR_SHIFT");
  L.push("");
  L.push("        # --- Saturate ------------------------------------------------");
  L.push("        spec[spec >= (SAT_MAX + 1)] = SAT_MAX");
  L.push("");
  L.push("        # --- Mel filterbank + Accumulate -----------------------------");
  L.push('        mels = np.dot(spec.astype("int32"), intfltrs.T.astype("int32"))');
  L.push("        mels = mels & 0xffff");
  L.push("");
  L.push("        # --- Log ------------------------------------------------------");
  L.push("        features = np.array(safe_log(mels), dtype=np.int16)");
  L.push("        output.append(features)");
  L.push("");
  L.push("    return output");
  L.push("");
  L.push("");
 
  // ----- demo entry point -----
  L.push('if __name__ == "__main__":');
  L.push("    dummy = np.random.randint(-2000, 2000, CAPTURE_LEN).astype(np.short)");
  L.push("    feats = preprocess(dummy)");
  L.push('    print("frames:", len(feats), "| features/frame:", NUM_FILT)');
 
  return L.join("\n");
}
 
 
// =====================================================
// LIGHTWEIGHT PYTHON SYNTAX HIGHLIGHTER   — unchanged
// =====================================================
const KEYWORDS = new Set([
  "def", "return", "for", "in", "import", "from", "as", "if", "else",
  "elif", "while", "and", "or", "not", "class", "with", "lambda",
  "None", "True", "False", "pass", "yield",
]);
 
const BUILTINS = new Set([
  "np", "print", "range", "len", "int", "float", "self", "zip",
  "max", "min", "enumerate", "list",
]);
 
function esc(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
 
function highlight(code) {
  const re = /("""[\s\S]*?"""|'''[\s\S]*?'''|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|(#.*$)|\b(0x[0-9a-fA-F]+|\d+\.?\d*)\b|\b([A-Za-z_]\w*)\b/gm;
 
  let out = "";
  let last = 0;
  let m;
 
  while ((m = re.exec(code))) {
    out += esc(code.slice(last, m.index));
 
    if (m[1]) {
      out += '<span class="pp-str">' + esc(m[1]) + "</span>";
    } else if (m[2]) {
      out += '<span class="pp-com">' + esc(m[2]) + "</span>";
    } else if (m[3]) {
      out += '<span class="pp-num">' + esc(m[3]) + "</span>";
    } else if (m[4]) {
      const word = m[4];
      if (KEYWORDS.has(word)) {
        out += '<span class="pp-kw">' + word + "</span>";
      } else if (BUILTINS.has(word)) {
        out += '<span class="pp-bi">' + word + "</span>";
      } else {
        const before = code.slice(0, m.index);
        if (/def\s+$/.test(before)) {
          out += '<span class="pp-def">' + word + "</span>";
        } else {
          out += word;
        }
      }
    }
 
    last = re.lastIndex;
  }
 
  out += esc(code.slice(last));
 
  return out
    .split("\n")
    .map((line, i) => '<span class="pp-ln">' + (i + 1) + "</span>" + line)
    .join("\n");
}
 
 
// =====================================================
// FRAME SLIDER  (draggable; snaps to whole 32 ms frames)
// =====================================================
function FrameSlider({ value, min, max, onChange, tip, avoidRef }) {
  const trackRef = useRef(null);
  const tipRef = useRef(null);
  const [dragging, setDragging] = useState(false);
  const [tipBelow, setTipBelow] = useState(false);
 
  const v = Math.max(min, Math.min(max, value));
  const pct = ((v - min) / (max - min)) * 100;
 
  // Tooltip sits above the thumb, except where that would cover the 1s..5s
  // preset buttons — there it flips below. avoidRef is the button row; measure
  // the buttons themselves (their flex parent stretches the full column width).
  useEffect(() => {
    const track = trackRef.current;
    const tipEl = tipRef.current;
    const row = avoidRef && avoidRef.current;
    if (!track || !tipEl || !row) return;
 
    const decide = () => {
      const kids = Array.from(row.children);
      if (!kids.length) return setTipBelow(false);
 
      const rects = kids.map((k) => k.getBoundingClientRect());
      const btnLeft = Math.min(...rects.map((r) => r.left));
      const btnRight = Math.max(...rects.map((r) => r.right));
 
      const t = track.getBoundingClientRect();
      const half = (tipEl.offsetWidth || 46) / 2 + 4;   // +4px breathing room
      const cx = t.left + (pct / 100) * t.width;
 
      setTipBelow(cx + half > btnLeft && cx - half < btnRight);
    };
 
    decide();
    window.addEventListener("resize", decide);
    return () => window.removeEventListener("resize", decide);
  }, [pct, tip, avoidRef]);
 
  const valueFromX = useCallback(
    (clientX) => {
      const el = trackRef.current;
      if (!el) return v;
      const r = el.getBoundingClientRect();
      const ratio = Math.min(1, Math.max(0, (clientX - r.left) / r.width));
      return Math.round(min + ratio * (max - min));
    },
    [min, max, v]
  );
 
  const down = (e) => {
    e.preventDefault();
    setDragging(true);
    e.currentTarget.setPointerCapture?.(e.pointerId);
    onChange(valueFromX(e.clientX));
  };
  const move = (e) => {
    if (dragging) onChange(valueFromX(e.clientX));
  };
  const up = (e) => {
    setDragging(false);
    e.currentTarget.releasePointerCapture?.(e.pointerId);
  };
  const key = (e) => {
    const clamp = (n) => Math.max(min, Math.min(max, n));
    let next = null;
    if (e.key === "ArrowRight" || e.key === "ArrowUp") next = v + 1;
    else if (e.key === "ArrowLeft" || e.key === "ArrowDown") next = v - 1;
    else if (e.key === "PageUp") next = v + 8;
    else if (e.key === "PageDown") next = v - 8;
    else if (e.key === "Home") next = min;
    else if (e.key === "End") next = max;
    if (next !== null) {
      e.preventDefault();
      onChange(clamp(next));
    }
  };
 
  const stepTick = max - min > 80 ? 2 : 1;
  const ticks = [];
  for (let i = min; i <= max; i += stepTick) {
    const p = ((i - min) / (max - min)) * 100;
    ticks.push(
      <span
        key={i}
        className={
          "pp-cap-tick" + (i <= v ? " on" : "") + ((i - min) % 5 === 0 ? " major" : "")
        }
        style={{ left: p + "%" }}
      />
    );
  }
 
  return (
    <div
      ref={trackRef}
      className={"pp-cap-track" + (dragging ? " dragging" : "")}
      onPointerDown={down}
      onPointerMove={move}
      onPointerUp={up}
      onPointerCancel={up}
    >
      <div className="pp-cap-tickrow">{ticks}</div>
      <div className="pp-cap-fill" style={{ width: pct + "%" }} />
      <div
        className="pp-cap-thumb"
        style={{ left: pct + "%" }}
        role="slider"
        tabIndex={0}
        aria-label="Capture length in 32 ms frames"
        aria-valuemin={min}
        aria-valuemax={max}
        aria-valuenow={v}
        aria-valuetext={tip}
        onKeyDown={key}
      >
        <span className={"pp-cap-tip" + (tipBelow ? " below" : "")} ref={tipRef}>{tip}</span>
      </div>
    </div>
  );
}
 
 
// =====================================================
// MAIN COMPONENT: Preprocessing
// =====================================================
function Preprocessing() {
 
  // =====================================================
  // STATE
  // =====================================================
  const [state, setState] = useState({
    square: true,
    saturate: true,
    full: false,       // Path 04 · full feature pipeline
    frame: 256,
    fftShift: 7,
    sqrShift: 8,
    satMax: 32767,
    features: 16,       // num_filt  (8 | 16)
    capture: 7936,     // 30 frames × 256 = 0.96 s @ 8 kHz
  });
  const [codeVisible, setCodeVisible] = useState(false);
  const [scanning, setScanning] = useState(false);
  const [toastMsg, setToastMsg] = useState("");
  const [toastShow, setToastShow] = useState(false);
  const [codeShown, setCodeShown] = useState(0);
  const [generating, setGenerating] = useState(false);
 
  // =====================================================
  // REFS
  // =====================================================
  const toastTimer = useRef(null);
  const scanTimer = useRef(null);
  const codeTimer = useRef(null);
  const codeBodyRef = useRef(null);
  const codeRef = useRef("");
  const capPresetsRef = useRef(null);   // 1s..5s button row — slider tip dodges it
 
  const { square: sq, saturate: sat, full } = state;
  const features = state.features;
  const frames = Math.max(0, Math.floor(state.capture / state.frame));
 
  // =====================================================
  // DERIVED VALUES
  // =====================================================
  const currentCode = full ? buildFullCode(state) : buildCode(state);
  codeRef.current = currentCode;
  const codeFile = full
    ? `feature_extraction_${features}feat_${state.capture}smp.py`
    : `preprocess_fft${sq ? "_square_shift" : ""}${sat ? "_saturate" : ""}.py`;
 
  const highlightedLines = highlight(currentCode).split("\n");
  const displayedHTML = codeVisible
    ? highlightedLines.slice(0, codeShown).join("\n")
    : highlightedLines.join("\n");
  const codeHTML =
    displayedHTML + (generating ? '<span class="pp-code-caret"></span>' : "");
 
  // ----- capture-length time math + viz data -----
  const frameMs = (state.frame / SAMPLE_RATE) * 1000;      // 32 ms
  const captureMs = (state.capture / SAMPLE_RATE) * 1000;  // total ms
  const captureSec = captureMs / 1000;                     // total seconds
 
  // Frames that best represent a given whole-second target (snaps to 32 ms).
  const framesForSec = (sec) =>
    Math.min(MAX_FRAMES, Math.max(MIN_FRAMES, Math.round((sec * SAMPLE_RATE) / state.frame)));
 
  // Clickable presets: 1s · 2s · 3s · 4s · 5s (snap to nearest whole frame).
  const capPresets = [1, 2, 3, 4, 5].map((sec) => ({
    sec,
    label: sec + " s",
    f: framesForSec(sec),
  }));
 
  // Non-clickable axis under the slider: same 1s..5s scale, positioned by %.
  const capAxis = [1, 2, 3, 4, 5].map((sec) => {
    const exactFrames = (sec * SAMPLE_RATE) / state.frame; // may be fractional
    const pct = Math.min(100, ((exactFrames - MIN_FRAMES) / (MAX_FRAMES - MIN_FRAMES)) * 100);
    return { sec, pct };
  });
 
  const capDividers = [];
  for (let i = 1; i < frames; i++) capDividers.push((i * WAVE.W) / Math.max(1, frames));
  const capCells = [];
  for (let k = 0; k < frames; k++) if (k % 2 === 0) capCells.push(k);
 
  // route chips
  const chipSeq = [
    { n: "TM-BUFFER", on: true },
    { n: "FFT", on: true },
    { n: "SQUARE", on: sq || full, opt: true },
    { n: "SHIFT", on: sq || full, opt: true },
    { n: "SATURATE", on: sat || full, opt: true },
    { n: "MEL FB", on: full, opt: true },
    { n: "ACCUMULATE", on: full, opt: true },
    { n: "LOG₂", on: full, opt: true },
  ];
 
  const pathSummary = (() => {
    const parts = ["FFT"];
    if (sq || full) parts.push("Square", "Shift");
    if (sat || full) parts.push("Saturate");
    if (full) parts.push("Mel", "Accumulate", "Log");
    return parts.join(" → ");
  })();
 
  // ----- flow-diagram model (compact, straight left→right, uniform shape) ---
  const NW = 104, NH = 60, NG = 32, X0 = 12, FLOW_Y = 18;
  const rowY = FLOW_Y;
  const rowCY = FLOW_Y + NH / 2;
  const chain = [
    { id: "buf", lbl: "TM-BUF", sub: "256-frame", on: true, mand: true },
    { id: "fft", lbl: "FFT", sub: "real » " + state.fftShift, on: true, mand: true },
    { id: "sqr", lbl: "SQUARE", sub: "x²", on: sq || full },
    { id: "shf", lbl: "SHIFT", sub: "» " + state.sqrShift, on: sq || full },
    { id: "sat", lbl: "SATURATE", sub: "clamp 16b", on: sat || full },
    { id: "mel", lbl: "MEL FB", sub: features + "×tri", on: full },
    { id: "acc", lbl: "ACCUM", sub: "& 0xffff", on: full },
    { id: "log", lbl: "LOG₂", sub: "0–15", on: full },
  ];
  const nodeX = (i) => X0 + i * (NW + NG);
  const lastOn = chain.reduce((a, s, i) => (s.on ? i : a), 0);
  const outX = nodeX(chain.length - 1) + NW + 30;  // arrow tip, far right (clear of the LOG₂ node)
  const railY = FLOW_Y + NH + 50;                  // bypass rail under the row
  const vbW = outX + 92;
  const vbH = railY + 18;
 
  // All stages share ONE uniform rounded-rect shape — clean, consistent flow.
  const renderShape = (s, i) => {
    const x = nodeX(i), y = rowY, w = NW, h = NH;
    return <rect className="pp-box" x={x} y={y} width={w} height={h} rx="10" />;
  };
 
  // =====================================================
  // HANDLERS
  // =====================================================
  const toast = useCallback((msg) => {
    setToastMsg(msg);
    setToastShow(true);
    clearTimeout(toastTimer.current);
    toastTimer.current = setTimeout(() => setToastShow(false), 1800);
  }, []);
 
  const applyPreset = (square, saturate) =>
    setState((s) => ({ ...s, square, saturate, full: false }));
 
  const applyFull = () =>
    setState((s) => ({ ...s, square: true, saturate: true, full: true }));
 
  const setFeatures = (n) => setState((s) => ({ ...s, features: n }));
 
  const setFrames = (f) =>
    setState((s) => ({
      ...s,
      capture: Math.max(MIN_FRAMES, Math.min(MAX_FRAMES, f)) * s.frame,
    }));
  const bumpFrames = (dir) => setFrames(frames + dir);
 
  const handleGenerate = () => setCodeVisible(true);
  const handleBack = () => setCodeVisible(false);
 
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(currentCode);
      toast("✓ Code copied to clipboard");
    } catch {
      toast("Copy failed — select manually");
    }
  };
 
  const handleDownload = () => {
    const blob = new Blob([currentCode], { type: "text/x-python" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = codeFile;
    a.click();
    URL.revokeObjectURL(a.href);
    toast("↓ " + a.download + " downloaded");
  };
 
  // =====================================================
  // GENERATION ANIMATION  (code "typing")
  // =====================================================
  useEffect(() => {
    clearInterval(codeTimer.current);
    clearTimeout(scanTimer.current);
 
    if (!codeVisible) {
      setCodeShown(0);
      setGenerating(false);
      setScanning(false);
      return;
    }
 
    const totalCode = codeRef.current.split("\n").length;
    const reduce =
      typeof window !== "undefined" &&
      window.matchMedia &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches;
 
    if (reduce) {
      setCodeShown(totalCode);
      setGenerating(false);
      return;
    }
 
    setCodeShown(0);
    setGenerating(true);
 
    const codeStep = Math.max(9, Math.floor(1600 / Math.max(1, totalCode)));
    let ci = 0;
    codeTimer.current = setInterval(() => {
      ci += 1;
      setCodeShown(ci);
      if (ci >= totalCode) {
        clearInterval(codeTimer.current);
        setGenerating(false);
        setScanning(true);
        scanTimer.current = setTimeout(() => setScanning(false), 1000);
      }
    }, codeStep);
 
    return () => {
      clearInterval(codeTimer.current);
      clearTimeout(scanTimer.current);
    };
  }, [codeVisible]);
 
  useEffect(() => {
    const el = codeBodyRef.current;
    if (!el) return;
    el.scrollTop = generating ? el.scrollHeight : 0;
  }, [codeShown, generating]);
 
  // =====================================================
  // CLEANUP
  // =====================================================
  useEffect(
    () => () => {
      clearTimeout(toastTimer.current);
      clearTimeout(scanTimer.current);
      clearInterval(codeTimer.current);
    },
    []
  );
 
  // =====================================================
  // RENDER
  // =====================================================
  return (
    <div className="pp">
      <main className="pp-main">
        <div className={`pp-stage${codeVisible ? " go-code" : ""}`}>
 
          {/* ===================================================
              SCREEN 1 — CONFIG
              =================================================== */}
          <section className={`pp-screen pp-config${full ? " is-full" : ""}`}>
 
            <div className="pp-config-body">
 
              {/* hero */}
              <div className="pp-hero">
                <h1 className="pp-title">Pre-Processing</h1>
              </div>
 
              {/* two columns: flow diagram (left) + variant picker (right) */}
              <div className="pp-grid">
 
                {/* LEFT — flow diagram */}
                <div className="pp-left">
                  <div className="pp-head">
                    <h2>
                      <span className="pp-eyebrow">FLOW</span>
                      {full ? "Full feature pipeline" : "Pre-processing route"}
                    </h2>
                  </div>
 
                  <div className="pp-diagram">
                    <div className="pp-svg-scroll">
                      <svg className="pp-flow" viewBox={`0 0 ${vbW} ${vbH}`} preserveAspectRatio="xMidYMid meet">
 
                        <defs>
                          <marker id="ppArrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto">
                            <path d="M0 0 L6 3 L0 6 Z" fill="#52d824" />
                          </marker>
                        </defs>
 
                        {/* straight connectors between consecutive stages */}
                        {chain.slice(0, -1).map((s, i) => {
                          const on = chain[i].on && chain[i + 1].on;
                          return (
                            <line
                              key={`w${i}`}
                              className={`pp-wire${on ? " on" : " dim"}`}
                              x1={nodeX(i) + NW} y1={rowCY} x2={nodeX(i + 1)} y2={rowCY}
                              markerEnd={on ? "url(#ppArrow)" : undefined}
                            />
                          );
                        })}
 
                        {/* route to output */}
                        {lastOn === chain.length - 1 ? (
                          <line
                            className="pp-wire on"
                            x1={nodeX(lastOn) + NW} y1={rowCY} x2={outX} y2={rowCY}
                            markerEnd="url(#ppArrow)"
                          />
                        ) : (
                          <path
                            className="pp-wire on bypass"
                            d={`M${nodeX(lastOn) + NW} ${rowCY} H${nodeX(lastOn) + NW + NG / 2} V${railY} H${outX - 14} V${rowCY} H${outX}`}
                            markerEnd="url(#ppArrow)"
                          />
                        )}
                        <text className="pp-io hot" x={outX + 8} y={rowCY - 5} textAnchor="start">
                          {full ? "features" : "output"}
                        </text>
                        <text className="pp-io" x={outX + 8} y={rowCY + 9} textAnchor="start">→ to model</text>
 
                        {/* stage nodes */}
                        {chain.map((s, i) => (
                          <g
                            key={s.id}
                            className={
                              `pp-node ${s.on ? "on" : "off"}` +
                              (s.mand ? " mand" : "") +
                              (s.on && s.mand ? " pp-node-pulse" : "")
                            }
                          >
                            {renderShape(s, i)}
                            <text className="pp-node-lbl" x={nodeX(i) + NW / 2} y={rowCY - 2} textAnchor="middle">{s.lbl}</text>
                            <text className="pp-node-sub" x={nodeX(i) + NW / 2} y={rowCY + 12} textAnchor="middle">{s.sub}</text>
                          </g>
                        ))}
                      </svg>
                    </div>
 
                    {/* route chips */}
                    <div className="pp-chips">
                      {chipSeq.map((s, i) => (
                        <Fragment key={s.n}>
                          <span className={s.on ? "pp-chip on" : s.opt ? "pp-chip skip" : "pp-chip"}>{s.n}</span>
                          {i < chipSeq.length - 1 && <span className="pp-arrow">▸</span>}
                        </Fragment>
                      ))}
                    </div>
                  </div>
                </div>
 
                {/* RIGHT — variant picker */}
                <div className="pp-right">
                  <div className="pp-head"><h2><span className="pp-eyebrow">CONFIG</span> Choose pre-processing route</h2></div>
 
                  <div className={`pp-presets${full ? " pp-presets-full" : ""}`}>
                    <button className={`pp-preset${!full && !sq && !sat ? " is-active" : ""}`} onClick={() => applyPreset(false, false)}>
                      <div className="pp-pno">PATH 01</div>
                      <div className="pp-pname">FFT</div>
                      <div className="pp-pdesc">Perform 256-point FFT.</div>
                    </button>
 
                    <button className={`pp-preset${!full && sq && !sat ? " is-active" : ""}`} onClick={() => applyPreset(true, false)}>
                      <div className="pp-pno">PATH 02</div>
                      <div className="pp-pname">FFT → Square → Shift</div>
                      <div className="pp-pdesc">256-point FFT followed by Square &amp; Shift.</div>
                    </button>
 
                    <button className={`pp-preset${!full && sq && sat ? " is-active" : ""}`} onClick={() => applyPreset(true, true)}>
                      <div className="pp-pno">PATH 03</div>
                      <div className="pp-pname">FFT → Square → Shift → Saturate</div>
                      <div className="pp-pdesc">256-point FFT·Square·Shift then clamp to 16-bit.</div>
                    </button>
 
                    <button className={`pp-preset is-full${full ? " is-active" : ""}`} onClick={applyFull}>
                      <div className="pp-pno">PATH 04</div>
                      <div className="pp-pname">
                        Full Pipeline <span className="pp-tag">FEATURES</span>
                      </div>
                      <div className="pp-pdesc">
                        FFT → Square → Shift → Saturate → Mel → Accumulate → Log. Emits the final int16 feature map.
                      </div>
                    </button>
                  </div>
                </div>
              </div>
 
              {/* ===================================================
                  PATH-04 CAPTURE CARD  (v3 — one compact band)
                  =================================================== */}
              {full && (
                <div className="pp-capbar">
 
                  {/* COLUMN 1 — capture length + slider */}
                  <div className="pp-cap-slider">
                    <div className="pp-cap-top">
                      <span className="pp-opt-label">Capture length</span>
                      <span className="pp-cap-readout">
                        <span className="pp-cap-sec">{captureSec.toFixed(2)}<i>s</i></span>
                        <span className="pp-cap-secsub">
                          {frames} frame{frames === 1 ? "" : "s"}
                        </span>
                      </span>
                    </div>
 
                    {/* clickable presets: 1s · 2s · 3s · 4s · 5s */}
                    <div className="pp-cap-presets" ref={capPresetsRef}>
                      {capPresets.map((p) => (
                        <button
                          key={p.sec}
                          className={`pp-cap-preset${frames === p.f ? " on" : ""}`}
                          onClick={() => setFrames(p.f)}
                        >{p.label}</button>
                      ))}
                    </div>
 
                    {/* draggable slider */}
                    <div className="pp-cap-sliderwrap">
                      <button
                        className="pp-cap-nudge"
                        onClick={() => bumpFrames(-1)}
                        disabled={frames <= MIN_FRAMES}
                        aria-label="remove one 32 ms frame"
                      >−</button>
 
                      <FrameSlider
                        value={frames}
                        min={MIN_FRAMES}
                        max={MAX_FRAMES}
                        onChange={setFrames}
                        tip={`${captureSec.toFixed(2)} s`}
                        avoidRef={capPresetsRef}
                      />
 
                      <button
                        className="pp-cap-nudge"
                        onClick={() => bumpFrames(1)}
                        disabled={frames >= MAX_FRAMES}
                        aria-label="add one 32 ms frame"
                      >+</button>
                    </div>
 
                    {/* fixed 1s..5s axis (display only) */}
                    <div className="pp-cap-axis">
                      {capAxis.map((a) => (
                        <span key={a.sec} style={{ left: a.pct + "%" }}>{a.sec}s</span>
                      ))}
                    </div>
                  </div>
 
                  {/* COLUMN 2 — right panel: Features + Output (side by side), scope below */}
                  <div className="pp-cap-right">
                    <div className="pp-cap-controls">
                      <div className="pp-opt">
                        <span className="pp-opt-label">Features</span>
                        <div className="pp-seg" role="group" aria-label="Feature count">
                          <button className={`pp-seg-btn${features === 8 ? " on" : ""}`} onClick={() => setFeatures(8)}>8</button>
                          <button className={`pp-seg-btn${features === 16 ? " on" : ""}`} onClick={() => setFeatures(16)}>16</button>
                        </div>
                      </div>
 
                      <div className="pp-opt">
                        <span className="pp-opt-label">Output map</span>
                        <div className="pp-cap-outbox">
                          <b>{frames} × {features}</b>
                          <small>{(frames * features).toLocaleString()} int16</small>
                        </div>
                      </div>
                    </div>
 
                    <div className="pp-cap-vizcol">
                      <span className="pp-opt-label">Frame · {frames} × 32 ms</span>
                      <div className="pp-cap-scope">
                        <svg viewBox={`0 0 ${WAVE.W} ${WAVE.H}`} preserveAspectRatio="none" className="pp-cap-wave">
                          {capCells.map((k) => (
                            <rect
                              key={"cc" + k}
                              x={(k * WAVE.W) / Math.max(1, frames)}
                              y="0"
                              width={WAVE.W / Math.max(1, frames)}
                              height={WAVE.H}
                              className="pp-cap-cell"
                            />
                          ))}
                          <line x1="0" y1={WAVE.H / 2} x2={WAVE.W} y2={WAVE.H / 2} className="pp-cap-base" />
                          <polyline points={WAVE.pts} className="pp-cap-trace" />
                          {capDividers.map((x, i) => (
                            <line key={"cd" + i} x1={x} y1="0" x2={x} y2={WAVE.H} className="pp-cap-div" />
                          ))}
                        </svg>
                      </div>
                    </div>
                  </div>
 
                </div>
              )}
 
            </div>{/* /pp-config-body */}
 
            {/* generate bar — always-visible footer */}
            <div className="pp-genbar">
              <div className="pp-pathline">
                Current path&nbsp;:&nbsp;<span className="pp-path">{pathSummary}</span>
              </div>
              <button className="pp-btn pp-btn-primary" onClick={handleGenerate}>
                Generate Python code
              </button>
            </div>
          </section>
 
          {/* ===================================================
              SCREEN 2 — CODE
              =================================================== */}
          <section className="pp-screen pp-codescreen">
            <div className="pp-code-layout">
              <div className={`pp-code-shell${scanning ? " scanning" : ""}`}>
                <div className="pp-code-scan" />
                <div className="pp-code-top">
                  <button className="pp-miniback" onClick={handleBack}>← Back</button>
                  <div className="pp-code-left">
                    <span className="pp-dots"><i /><i /><i /></span>
                    <span className="pp-code-file">{codeFile}</span>
                    {generating && <span className="pp-gen-tag">generating…</span>}
                  </div>
                  <div className="pp-code-actions">
                    <button className="pp-mini" onClick={handleCopy} disabled={generating}>⧉ Copy</button>
                    <button className="pp-mini" onClick={handleDownload} disabled={generating}>↓ Download</button>
                  </div>
                </div>
                <pre className="pp-code" ref={codeBodyRef} dangerouslySetInnerHTML={{ __html: codeHTML }} />
              </div>
            </div>
          </section>
 
        </div>
      </main>
 
      {/* ================= TOAST ================= */}
      <div className={`pp-toast${toastShow ? " show" : ""}`}>{toastMsg}</div>
    </div>
  );
}
 
// =====================================================
// EXPORT
// =====================================================
export default Preprocessing;
 
 